export { default as LectureApplyListPage } from './apply'
export { default as LectureCompletePage } from './complete'
export { default as LectureDetailPage } from './detail'
export { default as LecturePage } from './page'
export { default as LectureWritePage } from './write'
