import type { Metadata } from 'next'
import { GlobalLayout } from '@bitgouel/common/src/layouts'
import '@bitgouel/common/src/styles/globals.css'
import { Header } from '@bitgouel/common/src/components'
import RecoilRootProvider from './recoilRootProvider'
import localFont from 'next/font/local' 

export const metadata: Metadata = {
  title: '빛고을직업교육혁신지구',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

const pretendard = localFont({
  src: [
    {
      path: './fonts/woff/Pretendard-SemiBold.woff',
      weight: '600',
      style: 'normal'
    },
    {
      path: './fonts/woff/Pretendard-Medium.woff',
      weight: '500',
      style: 'normal'
    },
    {
      path: './fonts/woff/Pretendard-Regular.woff',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/woff2/Pretendard-SemiBold.woff2',
      weight: '600',
      style: 'normal'
    },
    {
      path: './fonts/woff2/Pretendard-Medium.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: './fonts/woff2/Pretendard-Regular.woff2',
      weight: '400',
      style: 'normal'
    },
  ],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={pretendard.className}>
      <body>
        <RecoilRootProvider>
          <GlobalLayout>
            <Header is_admin={false} />
            {children}
            <div id='modal' />
          </GlobalLayout>
        </RecoilRootProvider>
      </body>
    </html>
  )
}
