export const accessToken: string = 'Bitgouel-accessToken'
export const refreshToken: string = 'Bitgouel-refreshToken'
export const accessExpiredAt: string = 'Bitgouel-accessExp'
export const refreshExpiredAt: string = 'Bitgouel-refreshExp'
export const Authority: string = 'Bitgouel-authority'