export { default as Arrow } from './svg/Arrow'
export { default as CanView } from './svg/CanView'
export { default as Check } from './svg/Check'
export { default as Circle } from './svg/Circle'
export { default as Filter } from './svg/Filter'
export { default as MegaPhone } from './svg/MegaPhone'
export { default as Message } from './svg/Message'
export { default as NotView } from './svg/NotView'
export { default as Person } from './svg/Person'
export { default as Plus } from './svg/Plus'
export { default as Question } from './svg/Question'
export { default as SettingCircle } from './svg/SettingCircle'
export { default as SettingOut } from './svg/SettingOut'
export { default as Surprise } from './svg/Surprise'
export { default as XIcon } from './svg/XIcon'
export { default as Chevron } from './svg/Chevron'
export { default as People } from './svg/People'

export * from './svg'
