export { default as LoginPage } from './login'
export { default as SignUpPage } from './signUp'
export { default as HomePage } from './home'
export { ClubDetailPage, StudentPage } from './club'
export { PostPage, PostDetailPage, PostCreatePage, PostModifyPage, NoticeDetailPage, NoticeModifyPage } from './post'
export { default as MyPage } from './my'
export { InquiryPage, InquiryDetailPage } from './inquiry'
