export * from './useGetLectureList'
export * from './useGetDetailLecture'
export * from './usePostLecture'
export * from './useGetInstructors'
export * from './useGetLines'
export * from './useGetDepartments'