import type { Metadata } from 'next'
import { GlobalLayout } from '@common/layouts'
import '@common/styles/globals.css'
import '@/styles/font.css'
import { Header } from '@common/components'
import RecoilRootProvider from './recoilRootProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <RecoilRootProvider>
          <GlobalLayout>
            <Header inside={false} />
            {children}
          </GlobalLayout>
        </RecoilRootProvider>
        <div id='modal' />
      </body>
    </html>
  )
}
