import type { Metadata } from 'next'
import { GlobalLayout } from '@bitgouel/common/src/layouts'
import '@bitgouel/common/src/styles/globals.css'
import '@/styles/font.css'
import { Header } from '@bitgouel/common/src/components'
import RecoilRootProvider from './recoilRootProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <RecoilRootProvider>
          <GlobalLayout>
            <Header />
            {children}
            <div id='modal' />
          </GlobalLayout>
        </RecoilRootProvider>
      </body>
    </html>
  )
}
