export { default as PostPage } from './page'
export { default as PostDetailPage } from './detail'
export { default as PostCreatePage } from './create'
export { default as PostModifyPage } from './modify'
export { default as NoticeDetailPage } from './notification/detail'
export { default as NoticeModifyPage } from './notification/modify'